#!/bin/bash
# OSIRIS Installation Script — portable, works from any git clone location.
# Usage: cd copilot-sdk-dnalang && bash install-osiris.sh

set -e

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║   OSIRIS Installation - Quantum Development CLI              ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Auto-detect SDK root from this script's location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SDK_ROOT="$SCRIPT_DIR"
BIN_DIR="$SDK_ROOT/bin"
DNALANG_DIR="$SDK_ROOT/dnalang"

echo "📁 SDK Root: $SDK_ROOT"
echo ""

# Step 1: Ensure bin/osiris is executable
if [ -f "$BIN_DIR/osiris" ]; then
    chmod +x "$BIN_DIR/osiris"
    echo "✓ Made bin/osiris executable"
else
    echo "✗ bin/osiris not found at $BIN_DIR/osiris"
    exit 1
fi

# Step 2: Create launcher script at ~/.local/bin/osiris
LAUNCHER_DIR="$HOME/.local/bin"
mkdir -p "$LAUNCHER_DIR"

# Remove existing launcher if present (may be root-owned from prior install)
if [ -f "$LAUNCHER_DIR/osiris" ] && [ ! -w "$LAUNCHER_DIR/osiris" ]; then
    rm -f "$LAUNCHER_DIR/osiris" 2>/dev/null || {
        echo "✗ Cannot overwrite $LAUNCHER_DIR/osiris (owned by another user)"
        echo "  Fix with: rm $LAUNCHER_DIR/osiris"
        exit 1
    }
fi

cat > "$LAUNCHER_DIR/osiris" << LAUNCHER_EOF
#!/usr/bin/env bash
# OSIRIS — Sovereign Quantum Copilot (DNA::}{::lang v51.843)
# Auto-generated by install-osiris.sh — edit SDK_ROOT if you move the repo.
set -euo pipefail

SDK_ROOT="$SDK_ROOT"
BOOTSTRAP="\${SDK_ROOT}/dnalang/src/dnalang_sdk/osiris_bootstrap.py"

export PYTHONPATH="\${SDK_ROOT}/dnalang/src:\${PYTHONPATH:-}"

if [ -f "\$BOOTSTRAP" ]; then
    exec python3 "\$BOOTSTRAP" "\$@"
else
    # Fallback: run bin/osiris directly
    exec python3 "\${SDK_ROOT}/bin/osiris" "\$@"
fi
LAUNCHER_EOF

chmod +x "$LAUNCHER_DIR/osiris"
echo "✓ Created launcher at $LAUNCHER_DIR/osiris"

# Step 3: Ensure ~/.local/bin is in PATH
SHELL_RC="$HOME/.bashrc"
[ -f "$HOME/.zshrc" ] && SHELL_RC="$HOME/.zshrc"

if echo "$PATH" | grep -q "$LAUNCHER_DIR"; then
    echo "✓ $LAUNCHER_DIR already in PATH"
elif grep -q '.local/bin' "$SHELL_RC" 2>/dev/null; then
    echo "✓ PATH entry already in $SHELL_RC"
else
    echo "" >> "$SHELL_RC"
    echo "# OSIRIS - DNALang Quantum Development CLI" >> "$SHELL_RC"
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$SHELL_RC"
    echo "✓ Added ~/.local/bin to PATH in $SHELL_RC"
fi

# Step 4: Set up Python environment
if [ -d "$DNALANG_DIR/.venv" ]; then
    echo "✓ Virtual environment found at $DNALANG_DIR/.venv"
elif [ -d "$DNALANG_DIR/venv" ]; then
    echo "✓ Virtual environment found at $DNALANG_DIR/venv"
else
    echo "⚠ No virtual environment found"
    echo "  Create one: cd $DNALANG_DIR && python3 -m venv .venv && source .venv/bin/activate && pip install -e '.[dev]'"
fi

# Step 5: Add convenience aliases (idempotent)
if ! grep -q "# OSIRIS Aliases" "$SHELL_RC" 2>/dev/null; then
    cat >> "$SHELL_RC" << 'ALIAS_EOF'

# OSIRIS Aliases
alias osiris-quantum='osiris quantum'
alias osiris-ccce='osiris ccce'
alias osiris-chat='osiris chat'
ALIAS_EOF
    echo "✓ Added convenience aliases"
else
    echo "✓ Aliases already present"
fi

# Step 6: Create desktop launcher (optional, Linux only)
if [ "$(uname)" = "Linux" ] && [ -d "$HOME/.local/share/applications" ]; then
    DESKTOP_FILE="$HOME/.local/share/applications/osiris.desktop"
    if [ ! -f "$DESKTOP_FILE" ]; then
        cat > "$DESKTOP_FILE" << DESKTOP_EOF
[Desktop Entry]
Name=OSIRIS Quantum Dev CLI
Comment=DNALang Quantum Development Environment
Exec=gnome-terminal -- bash -c "osiris; bash"
Icon=utilities-terminal
Terminal=true
Type=Application
Categories=Development;
DESKTOP_EOF
        echo "✓ Created desktop launcher"
    fi
fi

# Step 7: Test installation
echo ""
echo "🧪 Testing installation..."
export PATH="$LAUNCHER_DIR:$PATH"

if command -v osiris &> /dev/null; then
    echo "✓ osiris command is available ($(which osiris))"
else
    echo "⚠ osiris not in PATH yet — restart terminal or: source $SHELL_RC"
fi

# Step 8: Done
echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║   Installation Complete!                                      ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Activate now:  source $SHELL_RC"
echo ""
echo "Usage:"
echo "  osiris                                # Interactive CLI"
echo "  osiris chat                           # Chat mode"
echo "  osiris quantum bell                   # Quantum circuits"
echo "  osiris agent \"task\"                   # Agent orchestration"
echo "  osiris ccce                           # Consciousness metrics"
echo ""
